version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ruby
      POSTGRES_PASSWORD: pinkola
      POSTGRES_DB: ruby_production
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./ruby
      dockerfile: Dockerfile
    image: rails-backend
    container_name: rails-backend
    working_dir: /rails
    volumes:
      - ./ruby:/rails
      - ./ruby/config/master.key:/rails/config/master.key:ro
      - storage_data:/rails/storage
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 938c3ae34a5596256bd01f829dd3cd30
      RUBY_DATABASE_PASSWORD: pinkola
      DATABASE_HOST: postgres-db # <- adicionado para compatibilidade com database.yml
      DATABASE_PORT: 5432 # <- adicionado para compatibilidade com database.yml
      DATABASE_USERNAME: ruby
    depends_on:
      - db

volumes:
  db_data:
  storage_data:
